#!/usr/bin/env ansible-playbook
---
- name: Create K3S container.
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
     ssh_key: "{{ lookup('file', './authorized_keys/kruse') }}"
     password: "{{ lookup('password', '/dev/null') }}"
  collections: 
    community.general
  tasks:
  - name: Create new LXC container with minimal options.
    proxmox:
      vmid: '119'
      node: aegean
      api_user: 'root@pam'
      api_password: "{{ proxmox_api_password }}"
      api_host: aegean.pondiki.lan 
      validate_certs: false
      cores: 8
      cpus: 1
      memory: 8192
      swap: 0
      disk: 8182
      # Local storage is my only ext4 disk.
      # Mounting ext4 formatted volumes in ZFS did not work for me yet.
      # As suggested here: https://github.com/MarijnKoesen/kubernetes-in-proxmox-with-kubeadm-lxc-and-wireshark
      storage: local
      unprivileged: false
      onboot: true
      purge: true
      force: true
      pubkey: "{{ ssh_key }}"
      password: "{{ password }}"
      hostname: k3s.pondiki.lan
      netif: '{"net0":"name=eth0,gw=192.168.178.1,ip=192.168.178.119/24,bridge=vmbr0"}'
      searchdomain: pondiki.lan
      nameserver: 192.168.178.1
      state: present
      ostemplate: 'local:vztmpl/debian-11-standard_11.0-1_amd64.tar.gz'
      description: 'ELK - Created with care by Ansible'
      features: 
        - nesting=1
- name:  Add extra configuration for container on container host.
  hosts: aegean
  gather_facts: false
  become: false
  tasks:
  - name: Add extra configuration to container configuration file. 
    blockinfile:
      path: /etc/pve/lxc/119.conf
      block: |
        lxc.apparmor.profile: unconfined
        lxc.cgroup.devices.allow: a
        lxc.cap.drop:
        lxc.mount.auto: "proc:rw sys:rw"
- name:  Start KS container
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
     ssh_key: "{{ lookup('file', './authorized_keys/kruse') }}"
     password: "{{ lookup('password', '/dev/null') }}"
  collections: 
    community.general
  tasks:
  - name: Start newly created LXC container.
    proxmox:
      vmid: '119'
      node: aegean
      api_user: 'root@pam'
      api_password: "{{ proxmox_api_password }}"
      api_host: aegean.pondiki.lan 
      validate_certs: false
      state: started
