---
all:
  children:
    proxmox_servers:
      hosts:
        aegean:
          hostname: aegean.pondiki.lan
      vars:
        root_user_ssh_key: https://github.com/nicenemo.keys
    proxmox_debian_containers:
      children:
        k3s_hosts:
          hosts:
            k3s:
      vars:
        ansible_user: root
        ssh_user: root
        packages_to_install:
          - sudo
          - neovim
          - htop
          - tmux
          - syslog-ng
  vars:
    ansible_python_interpreter: /usr/bin/python3
    packages_to_install:
      - sudo
      - neovim
      - htop
      - tmux
    packages_to_remove:
      - vim
      - nano
