#!/usr/bin/env ansible-playbook
---
- name: Provision K3S.
  hosts: k3s_hosts
  become: true
  roles:
    - nicenemo.debianbase
  tasks:
   - name: Get K3S provisioning script.
     uri:
       url:  https://get.k3s.io
       dest: /tmp/k3s.sh
       mode: 0755
       owner: root
       group: root
   - name: Provision K3S.
     command:
       cmd: '/tmp/k3s.sh'       
