#!/usr/bin/env ansible-playbook
---
- name: Provision K3S.
  hosts: k3s_hosts
  become: true
  roles:
    - nicenemo.debianbase
  tasks:
    - name: Copy rc.local script.
      # From:
      # https://gist.github.com/triangletodd/02f595cd4c0dc9aac5f7763ca2264185
      # TODO: try a oneshot systemd service instead.
      copy:
        src: ./files/k3s/etc/rc.local
        dest: /etc/rc.local
        mode: 0700
        owner: root
        group: root
    - name: Execute rc.local.
      command:
        cmd: /etc/rc.local
    - name: Get K3S provisioning script.
      uri:
        url: https://get.k3s.io
        dest: /tmp/k3s.sh
        mode: 0755
        owner: root
        group: root
    - name: Provision K3S.
      command:
        cmd: '/tmp/k3s.sh'
