#!/usr/bin/env ansible-playbook
---
- name: Configure Proxmox base system.
  hosts: proxmox_servers
  become: true
  collections:
  - community.general
  - ansible.posix
  roles:
  - nicenemo.debianbase
  pre_tasks:
  - name: Install ssh key
    authorized_key:
      user: root
      key: '{{root_user_ssh_key }}'
  - name: Remove paid Proxmox apt repo pve-enterprise config.
    file:
      name: /etc/apt/sources.list.d/pve-enterprise.list
      state: absent
  - name: Add free Proxmox apt repo pve-no_subscription config.
    copy:
      src: proxmox/etc/apt/sources.list.d/pve-no-subscription.list
      dest: /etc/apt/sources.list.d/pve-no-subscription.list
  - name: Enlarge ipv4 forwarding
    # Needed for Kubernetes Metal LB
    lineinfile:
      path: /etc/sysctl.conf
      state: present
      line: 'net.ipv4.ip_forward=1'
    notify: sysctl changed
  - name: Enlarge virtual memory map.
    # Needed for Elasticsearch
    lineinfile:
      path: /etc/sysctl.conf
      state: present
      line: 'vm.max_map_count=262144'
    notify: sysctl changed
  - name: Set swapiness to 0.
    # Kubernetes can't work with swap enabled.
    lineinfile:
      path: /etc/sysctl.conf
      state: present
      line: 'vm.swapiness=0'
    notify: sysctl changed
  - name: Disable SWAP.
    # Kubernetes can't work with swap enabled.
    command:
      cmd: swapoff -a
    changed_when: false
  - name: Disable SWAP in fstab.
    # Kubernetes can't work with swap enabled.
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
  tasks:
    - name: Update Proxmox container images.
      command:
        cmd: 'pveam update'
      changed_when: false
    - name: Install images in local.
      command:
        cmd: "pveam download local {{ item }}"
      loop: "{{ container_images }}"
      changed_when: false
  handlers:
    - name: sysctl changed
      command:
        cmd: sysctl --system
