---
roles:
  - src: https://github.com/nicenemo/nicenemo.debianbase
    version: main
    name: nicenemo.debianbase
collections:
  - ansible.posix
  - community.docker
  - community.general
  - community.network
